# See https://github.com/golangci/golangci-lint/blob/master/.golangci.yml for more examples

linters:
    enabled:
        # In addition to default standard linters (see: golangci-lint help linters)
        # Try extra ones line this: golangci-lint run --disable-all --enable=lll
        - goimports
        - gocritic
        - golint
        - lll



