version = "2"

[linters]
enable = [
  "whitespace",
  "gosec",
  "gocritic",
  "bodyclose",
  "intrange",
  "misspell",
]

[linters.exclusions]
generated = "lax"
presets = [
  "comments",
  "common-false-positives",
  "legacy",
  "std-error-handling"
]
paths = [ "third_party$", "builtin$", "examples$" ]

[formatters]
enable = [ "goimports", "gofmt" ]

[formatters.exclusions]
generated = "lax"
paths = [ "third_party$", "builtin$", "examples$" ]
